GET http://localhost:6666/users HTTP/1.1

###

GET http://localhost:6666/users/1 HTTP/1.1

###

GET http://localhost:6666/users/1000 HTTP/1.1

###

POST http://localhost:6666/auth HTTP/1.1
Content-Type: application/json

{
    "username": "user 1",
    "password": "fdsfsdfdsfs@gdfgd.com"
}

###

POST http://localhost:6666/users HTTP/1.1
Content-Type: application/json

{
    "name": "cfghf",
    "email": "hkk@gmail.com",
    "tasks": [{"name":"taskss"}]
}

###

DELETE http://localhost:6666/users/1 HTTP/1.1
